# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/focal64"
  
    config.vm.define "docker" do |docker|
      docker.vm.hostname = "docker-server"
      docker.vm.provider "virtualbox" do |vb|
        vb.name = "docker-server"
        vb.cpus = 4
        vb.memory = 8192
      end
      docker.vm.network "forwarded_port", guest: 80, host: 80
      docker.vm.network "private_network", ip: "192.168.33.200"
      docker.vm.provision "shell", inline: <<-SCRIPT
       
      SCRIPT
    end
  
    
    config.vm.define "sshfs" do |sshfs|
        sshfs.vm.hostname = "sshfs-server"
        sshfs.vm.provider "virtualbox" do |vb|
          vb.name = "sshfs-server"
          vb.cpus = 1
          vb.memory = 2048
        end
        sshfs.vm.network "private_network", ip: "192.168.33.250"
        sshfs.vm.provision "shell", inline: <<-SCRIPT
         
        SCRIPT
      end
    end  