#user2 생성
apiVersion: v1
kind: ServiceAccount
metadata:
  name: user2
secrets:
  - apiVersion: v1
    kind: Secret 
    name: user2-secret
---
#user2 토큰생성
apiVersion: v1 
kind: Secret 
type: kubernetes.io/service-account-token
metadata:
  name: user2-secret
  annotations:
    kubernetes.io/service-account.name: user2
---
#롤생성
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: user2-role
  namespace: default
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get","list","watch"]
---
#롤바인딩생성
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: user2-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: user2
  apiGroup: ""
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: user2-role