Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/focal64"

    config.vm.define "db" do |db|
        db.vm.hostname = "db-server"
        db.vm.provider "virtualbox" do |vb|
            vb.name = "db-server"
            vb.cpus = 4
            vb.memory = 8192
        end
        db.vm.network "private_network", ip: "192.168.10.10"
    end
end