apiVersion: v1
kind: ServiceAccount
metadata: 
  name: user3
  namespace: user-space
secrets:
  - apiVersion: v1
    kind: Secret
    name: user3-secret
---
apiVersion: v1    
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: user3-secret
  namespace: user-space
  annotations:
    kubernetes.io/service-account.name: user3

















