Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/focal64"

    config.vm.define "primary" do |primary|
        primary.vm.hostname = "primary-server"
        primary.vm.provider "virtualbox" do |vb|
            vb.name = "primary-server"
            vb.cpus = 4
            vb.memory = 4096
        end
        primary.vm.network "private_network", ip: "192.168.10.10"
  end

    config.vm.define "secondary" do |secondary|
        secondary.vm.hostname = "secondary-server"
        secondary.vm.provider "virtualbox" do |vb|
            vb.name = "secondary-server"
            vb.cpus = 4
            vb.memory = 4096
        end
        secondary.vm.network "private_network", ip: "192.168.10.20"
  end


    config.vm.define "mongo3" do |mongo3|
        mongo3.vm.hostname = "mongo3-server"
        mongo3.vm.provider "virtualbox" do |vb|
            vb.name = "mongo3-server"
            vb.cpus = 4
            vb.memory = 4096
        end
        mongo3.vm.network "private_network", ip: "192.168.10.30"
    end


    config.vm.define "mongo4" do |mongo4|
        mongo4.vm.hostname = "mongo4-server"
        mongo4.vm.provider "virtualbox" do |vb|
            vb.name = "mongo4-server"
            vb.cpus = 4
            vb.memory = 4096
        end
        mongo4.vm.network "private_network", ip: "192.168.10.40"
    end


    config.vm.define "mongo5" do |mongo5|
        mongo5.vm.hostname = "mongo5-server"
        mongo5.vm.provider "virtualbox" do |vb|
            vb.name = "mongo5-server"
            vb.cpus = 4
            vb.memory = 4096
        end
        mongo5.vm.network "private_network", ip: "192.168.10.50"
    end


    config.vm.define "mongo6" do |mongo6|
        mongo6.vm.hostname = "mongo6-server"
        mongo6.vm.provider "virtualbox" do |vb|
            vb.name = "mongo6-server"
            vb.cpus = 4
            vb.memory = 4096
        end
        mongo6.vm.network "private_network", ip: "192.168.10.60"
    end


end