Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/focal64"

    config.vm.define "primary" do |primary|
        primary.vm.hostname = "primary-server"
        primary.vm.provider "virtualbox" do |vb|
            vb.name = "primary-server"
            vb.cpus = 4
            vb.memory = 4096
        end
        primary.vm.network "private_network", ip: "192.168.10.10"
  end

    config.vm.define "secondary" do |secondary|
        secondary.vm.hostname = "secondary-server"
        secondary.vm.provider "virtualbox" do |vb|
            vb.name = "secondary-server"
            vb.cpus = 4
            vb.memory = 4096
        end
        secondary.vm.network "private_network", ip: "192.168.10.20"
  end

end