Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/focal64"

    config.vm.define "db2" do |db2|
        db2.vm.hostname = "db2-server"
        db2.vm.provider "virtualbox" do |vb|
            vb.name = "db2-server"
            vb.cpus = 4
            vb.memory = 8192
        end
        db2.vm.network "private_network", ip: "192.168.10.10"
        db2.vm.provision "shell", inline: <<-SCRIPT
        sudo apt-get update -y
        sudo apt-get install -y ca-certificates curl gnupg lsb-release
        sudo install -m 0755 -d /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
        sudo chmod a+r /etc/apt/keyrings/docker.gpg
        echo \
        "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
        "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
        sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
        sudo apt-get update -y
        sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
        sudo usermod -a -G docker vagrant
        sudo systemctl enable docker
        sudo systemctl start docker
        docker login -u hedgehoon --password-stdin < /vagrant/env/docker_token
    SCRIPT
  end

    config.vm.define "docker" do |docker|
        docker.vm.hostname = "docker-server"
        docker.vm.provider "virtualbox" do |vb|
            vb.name = "docker-server"
            vb.cpus = 4
            vb.memory = 8192
        end
        docker.vm.network "private_network", ip: "192.168.10.20"
        docker.vm.provision "shell", inline: <<-SCRIPT
        sudo apt-get update -y
        sudo apt-get install -y ca-certificates curl gnupg lsb-release
        sudo install -m 0755 -d /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
        sudo chmod a+r /etc/apt/keyrings/docker.gpg
        echo \
        "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
        "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
        sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
        sudo apt-get update -y
        sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
        sudo usermod -a -G docker vagrant
        sudo systemctl enable docker
        sudo systemctl start docker
        docker login -u hedgehoon --password-stdin < /vagrant/env/docker_token
    SCRIPT
  end

end