Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/focal64"

    config.vm.define "mongo1" do |mongo1|
        mongo1.vm.hostname = "mongo1-server"
        mongo1.vm.provider "virtualbox" do |vb|
            vb.name = "mongo1-server"
            vb.cpus = 4
            vb.memory = 4096
        end
        mongo1.vm.network "private_network", ip: "192.168.10.10"
        mongo1.vm.network "public_network", ip: "192.168.101.180"
        mongo1.vm.provision "shell", path: "install_mongodb.sh"
    end
    
    config.vm.provision "file", source: "./install_mongodb.sh", destination: "/vagrant/install_mongodb.sh"
end